# Generated by Django 3.1.3 on 2020-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='profile_pictures/')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
