# Generated by Django 3.1.3 on 2020-11-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201130_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='users/profile_pictures/default.jpg', upload_to='users/profile_pictures/'),
        ),
    ]
