# Generated by Django 3.1.3 on 2020-11-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201130_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pictures/'),
        ),
    ]
