# Generated by Django 3.1.3 on 2020-12-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pictures/', verbose_name='User Image'),
        ),
    ]
