# Generated by Django 3.1.3 on 2020-11-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Task Name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('completed_on', models.DateTimeField(verbose_name='Completed On')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
