# Generated by Django 3.1.3 on 2020-12-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201130_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, verbose_name='Completed On'),
        ),
    ]
