# Generated by Django 3.1.3 on 2020-12-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201201_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='github_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='GitHub Link'),
        ),
    ]
