# Generated by Django 3.1.3 on 2020-12-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20201201_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed On'),
        ),
        migrations.AlterField(
            model_name='task',
            name='github_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='GitHub Link'),
        ),
    ]
