# Generated by Django 3.1.3 on 2021-01-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210111_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('todo', 'TODO'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=40, verbose_name='Status'),
        ),
    ]
